Training/eGift.Store.Razor/eGift.Store.Razor/Pages/Customer/Login.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using eGift.Store.Razor.Data;
using eGift.Store.Razor.Models.ViewModels;
using Microsoft.EntityFrameworkCore;
using System.Net;
using eGift.Store.Razor.Helpers;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;

namespace eGift.Store.Razor.Pages.Customer
{
    public class LoginModel : PageModel
    {
        #region Variables
        public WebApiHelper _webApiHelper;
        #endregion

        #region Constructors
        public LoginModel(IConfiguration configuration)
        {
            this._webApiHelper = new WebApiHelper(configuration);
            SigninViewModel = new SigninViewModel();
        }
        #endregion

        #region Properties
        [BindProperty]
        public SigninViewModel SigninViewModel { get; set; }
        #endregion

        #region Actions
        public void OnGet()
        {
            //return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            //Web API client call
            var response = _webApiHelper.WebApiClientGet(string.Format("api/Login/GetLoginCustomer?userName={0}&password={1}", SigninViewModel.UserName, SigninViewModel.Password));
            if (!string.IsNullOrWhiteSpace(response))
            {
                HttpContext.Session.SetString("UserName", SigninViewModel.UserName);

                var loginModel = JsonConvert.DeserializeObject<LoginViewModel>(response);
                loginModel.LoginDate = DateTime.Now;
                var modelData = JsonConvert.SerializeObject(loginModel);
                var saveLoginResponse = _webApiHelper.WebApiClientPost(string.Format("api/Login/SaveLoginDateTime"), modelData);

                if (!string.IsNullOrWhiteSpace(saveLoginResponse))
                {
                    var savedLoginModel = JsonConvert.DeserializeObject<LoginViewModel>(saveLoginResponse);
                    HttpContext.Session.SetInt32("UserId", savedLoginModel.RefId);
                    HttpContext.Session.SetString("LoginDate", savedLoginModel.LoginDate.ToString());
                    HttpContext.Session.SetString("LastLoginDate", savedLoginModel.LastLoginDate.ToString());
                }
                //Redirect to list
                return RedirectToPage("/Index");
            }

            return Page();
        }
        #endregion

        #region Login Handler Methods
        public IActionResult OnGetLogout()
        {
            //User session.
            HttpContext.Session.SetString("UserName", "");
            HttpContext.Session.SetInt32("UserId", 0);
            HttpContext.Session.SetString("LoginDate", "");
            HttpContext.Session.SetString("LastLoginDate", "");

            //Order session
            HttpContext.Session.Remove("Order");
            HttpContext.Session.Remove("OrderDetails");
            HttpContext.Session.Remove("AddToCartList");
            HttpContext.Session.Remove("ProductList");


            return RedirectToPage("/Index");
        }
        #endregion
    }
}

Training/eGift.Store.Razor/eGift.Store.Razor/Pages/Shared/_Layout.cshtml
    @using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor Accessor
@{
    ViewData["ApplicationName"] = "eGift.Store";
    var userName = @Accessor.HttpContext.Session.GetString("UserName");
    var userId = @Accessor.HttpContext.Session.GetInt32("UserId");
    var currentDate = @Accessor.HttpContext.Session.GetString("LoginDate");
    var lastDate = @Accessor.HttpContext.Session.GetString("LastLoginDate");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ViewData["ApplicationName"]</title>
    @*style sheets files*@
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    @*java scripts files*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">@ViewData["ApplicationName"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @if (!string.IsNullOrWhiteSpace(userName))
                    {
                        <ul id="account-logout" class="navbar-nav flex-grow-1 col-md-3 flex-sm-row-reverse">
                            <li class="nav-item">
                                <a class="nav-link text-dark font-weight-bold" asp-area="" asp-page="/Customer/Login" asp-page-handler="Logout">Logout</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Customer/Details" asp-route-id="@userId">My Profile</a>
                            </li>
                        </ul>
                    }
                    else
                    {
                        <ul id="account-login" class="navbar-nav flex-grow-1 col-md-3 flex-sm-row-reverse">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Customer/Login">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Customer/Create">Register</a>
                            </li>
                        </ul>
                    }
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>*@
                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>*@
                        @if (!string.IsNullOrWhiteSpace(userName))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-page="/Orders/Index">My Orders</a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - @ViewData["ApplicationName"] - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>