Training/eGift.Admin.MVC/eGift.Admin.MVC/eGift.Admin.MVC/Controllers/OrdersController.cs
using eGift.Admin.MVC.Common;
using eGift.Admin.MVC.Helpers;
using eGift.Admin.MVC.Models.ListViewModels;
using eGift.Admin.MVC.Models.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using System;
using System.Linq;

namespace eGift.Admin.MVC.Controllers
{
    public class OrdersController : Controller
    {
        #region Variables

        public IConfiguration _configuration;
        public WebApiHelper _webApiHelper;

        #endregion

        #region Constructors

        public OrdersController(IConfiguration configuration)
        {
            this._configuration = configuration;
            this._webApiHelper = new WebApiHelper(configuration);
        }

        #endregion
        #region Product Actions
        // GET: OrdersController
        public ActionResult Index()
        {
            var list = new OrderListViewModel();

            //Webapiclient call
            var ordersResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}", "Order"));
            if (!string.IsNullOrWhiteSpace(ordersResponse))
            {
                list.OrderList = JsonConvert.DeserializeObject<OrderViewModel[]>(ordersResponse).ToList();

                //Webapiclient call
                var customerResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}", "Customer"));
                if (!string.IsNullOrWhiteSpace(customerResponse))
                {
                    var customerList = JsonConvert.DeserializeObject<CustomerViewModel[]>(customerResponse).ToList();
                    list.OrderList = list.OrderList.Join(customerList, o => o.CustomerId, c => c.ID, (o, c) => new { o, c }).Select(m => { m.o.FirstName = m.c.FirstName; m.o.LastName = m.c.LastName; return m.o; }).ToList();

                }
                return View(list);
            }
            return View();
        }

        // GET: OrdersController/Details/5
        public ActionResult Details(int id)
        {
            {
                var orderModel = new OrderViewModel();

                //Webapiclient call
                var response = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}", "Order", id));
                if (!string.IsNullOrWhiteSpace(response))
                {
                    orderModel = JsonConvert.DeserializeObject<OrderViewModel>(response);

                    //Webapiclient call
                    var customerResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}", "Customer", orderModel.CustomerId));
                    if (!string.IsNullOrWhiteSpace(customerResponse))
                    {
                        var customer = JsonConvert.DeserializeObject<CustomerViewModel>(customerResponse);
                        orderModel.CustomerId = customer.ID;

                        orderModel.CustomerName = customer.Name;
                        orderModel.CustomerAddress = customer.AddressName;
                        orderModel.CustomerContact = customer.Mobile;
                        orderModel.StatusName = ((Status)orderModel.StatusId).ToString();
                    }

                    //Webapiclient call
                    var orderDetailsResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}?orderId={2}", "OrderDetails", "GetByOrderId", id));
                    if (!string.IsNullOrWhiteSpace(orderDetailsResponse))
                    {
                        orderModel.OrderDetailsList = JsonConvert.DeserializeObject<OrderDetailsViewModel[]>(orderDetailsResponse).ToList();
                    }

                    //Webapiclient call
                    var productsResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}", "Product"));
                    if (!string.IsNullOrWhiteSpace(productsResponse))
                    {
                        var productList = JsonConvert.DeserializeObject<ProductViewModel[]>(productsResponse).ToList();

                        //Join
                        orderModel.OrderDetailsList = orderModel.OrderDetailsList.Join(productList, od => od.ProductId, p => p.ID, (od, p) => new { od, p }).Select(m => { m.od.ProductName = m.p.Name; return m.od; }).ToList();
                    }
                }
                return View(orderModel);
            }
        }
        // GET: OrdersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OrdersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: OrdersController/Edit/5
        public ActionResult Edit(int id)
        {
            //Webapiclient call
            var response = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}", "Order", id));
            if (!string.IsNullOrWhiteSpace(response))
            {
                var OrderModel = JsonConvert.DeserializeObject<OrderViewModel>(response);
                OrderModel.StatusName = ((Status)OrderModel.StatusId).ToString();

                //Webapiclient call
                var customerResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}", "Customer", OrderModel.CustomerId));
                if (!string.IsNullOrWhiteSpace(customerResponse))
                {
                    var customer = JsonConvert.DeserializeObject<CustomerViewModel>(customerResponse);
                    OrderModel.CustomerId = customer.ID;

                    OrderModel.CustomerName = customer.Name;
                    OrderModel.CustomerAddress = customer.AddressName;
                    OrderModel.CustomerContact = customer.Mobile;
                }

                //Webapiclient call
                var orderDetailsResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}?orderId={2}", "OrderDetails", "GetByOrderId", id));
                if (!string.IsNullOrWhiteSpace(orderDetailsResponse))
                {
                    OrderModel.OrderDetailsList = JsonConvert.DeserializeObject<OrderDetailsViewModel[]>(orderDetailsResponse).ToList();
                }

                //Webapiclient call
                var productsResponse = _webApiHelper.WebApiClientGet(string.Format("api/{0}", "Product"));
                if (!string.IsNullOrWhiteSpace(productsResponse))
                {
                    var productList = JsonConvert.DeserializeObject<ProductViewModel[]>(productsResponse).ToList();

                    //Join
                    OrderModel.OrderDetailsList = OrderModel.OrderDetailsList.Join(productList, od => od.ProductId, p => p.ID, (od, p) => new { od, p }).Select(m => { m.od.ProductName = m.p.Name; return m.od; }).ToList();
                }
                return View(OrderModel);
            }
            return View();
        }

        // POST: OrdersController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, OrderViewModel model)
        {
            try
            {
                //Webapiclient call
                var response = _webApiHelper.WebApiClientGet(string.Format("api/{0}/{1}", "Order", id));
                if (!string.IsNullOrWhiteSpace(response))
                {
                    var order = JsonConvert.DeserializeObject<OrderViewModel>(response);

                    order.StatusId = model.StatusId;
                    if (model.StatusId == (int)Status.Dispatched)
                    {
                        order.DispatchDate = DateTime.Now;
                    }
                    else if (model.StatusId == (int)Status.Shipped)
                    {
                        order.ShippedDate = DateTime.Now;
                    }
                    else if (model.StatusId == (int)Status.Delievered)
                    {
                        order.DeliveryDate = DateTime.Now;
                    }
                    else if (model.StatusId == (int)Status.Cancelled)
                    {
                        order.CancelDate = DateTime.Now;
                    }
                    order.UpdatedBy = HttpContext.Session.GetInt32("UserId");
                    order.UpdatedDate = DateTime.Now;

                    //conver model to json string
                    var modelData = JsonConvert.SerializeObject(order);

                    // Web client call
                    var updateResponse = _webApiHelper.WebApiClientPost(string.Format("api/{0}", "Order"), modelData);
                    if (!string.IsNullOrWhiteSpace(updateResponse))
                    {
                        return RedirectToAction(nameof(Index));
                    }
                }
            }
            catch
            {
            }
            return View();
        }

        // GET: OrdersController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: OrdersController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        #endregion
    }
}

Training/eGift.Admin.MVC/eGift.Admin.MVC/eGift.Admin.MVC/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@inject IHttpContextAccessor Accessor
@{
    var userName = @Accessor.HttpContext.Session.GetString("UserName");
    var currentDate = Accessor.HttpContext.Session.GetString("LoginDate");
    var lastDate = Accessor.HttpContext.Session.GetString("LastLoginDate");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @ViewData["ApplicationName"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/css/style.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@ViewData["ApplicationName"]</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1 flex-sm-row-reverse">
                        <li class="nav-item font-weight-bolder">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                        </li>
                        @if (!string.IsNullOrWhiteSpace(userName))
                        {
                            <li class="nav-item ">
                                <span class="nav-link">Welcome, <b>@userName</b>!</span>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="Index">Customer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Country" asp-action="Index">Country</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="State" asp-action="Index">State</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">City</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Address</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Category</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SubCategory" asp-action="Index">SubCategory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Product</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="Index">Order</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            <div class="row">
                <div class=" col-4">
                    &copy; 2023 - @ViewData["ApplicationName"] - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>


                <div class="col-md-5 text-right pr-0">

                    @if (!string.IsNullOrWhiteSpace(currentDate))
                    {
                        <span class="nav-item">
                            <span>Login: <b>@Convert.ToDateTime(currentDate).ToString("dd-MM-yyyy hh:mm:tt")</b> | </span>
                        </span>
                    }

                </div>

                <div class="col-md-3 text-right">

                    @if (!string.IsNullOrWhiteSpace(lastDate))
                    {
                        <span class="nav-item">
                            <span>Last Login: <b>@Convert.ToDateTime(lastDate).ToString("dd-MM-yyyy hh:mm:tt")</b> | </span>
                        </span>
                    }

                </div>
            </div>
        </div>
    </footer>
    @RenderSection("Scripts", required: false)
</body>
</html>